# Generated by Django 4.0.3 on 2022-03-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_fulling_options_alter_milktank_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulling',
            name='date',
            field=models.DateField(default='2022-02-02', verbose_name='Время заливки'),
        ),
    ]
