# Generated by Django 4.0.3 on 2022-03-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_fulling_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulling',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Время заливки'),
        ),
    ]
