# Generated by Django 4.0.3 on 2022-03-13 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_fulling_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя работника')),
                ('info', models.TextField(verbose_name='О работнике')),
                ('start_date', models.DateField(auto_now=True, verbose_name='Дата приема на работу')),
                ('salary', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='fulling',
            options={'verbose_name': 'Заливка', 'verbose_name_plural': 'Заливки'},
        ),
        migrations.AlterField(
            model_name='fulling',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.worker'),
        ),
    ]
