# Generated by Django 4.0.3 on 2022-03-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_delete_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя рабочего')),
                ('start_date', models.DateField(auto_now=True, verbose_name='Дата приема на работу')),
                ('salary', models.IntegerField(verbose_name='Оклад')),
            ],
        ),
    ]
