# Generated by Django 4.0.3 on 2022-03-14 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_worker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterField(
            model_name='fulling',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.worker'),
        ),
    ]
