# Generated by Django 4.0.3 on 2022-03-11 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MilkTank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullness', models.IntegerField(verbose_name='Числовой показатель заполненности')),
            ],
        ),
        migrations.CreateModel(
            name='Fulling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя заливающего')),
                ('liters', models.IntegerField(verbose_name='Число залитых литров')),
                ('comment', models.CharField(max_length=50, verbose_name='Комментарий к заливке')),
                ('milk_tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.milktank')),
            ],
        ),
    ]
