# Generated by Django 4.0.3 on 2022-03-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_worker_alter_fulling_options_alter_fulling_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulling',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя заливающего'),
        ),
    ]
