# Generated by Django 4.0.3 on 2022-03-14 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_fulling_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
